version: '3'
services:
  app:
    build: ./client/
    volumes:
      - ./client/:/app
    ports:
      - "3000:3000"
    command: ash -c "yarn install && yarn run dev"
    environment:
      API_URL: "http://api:5432"
  api:
    build: ./server/.
    volumes:
      - ./server/:/app
    ports:
      - "5432:5432"
  db:
    image: mysql:5.7
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
      TZ: "Asia/Tokyo"
  db_volume:
    image: busybox:1.29.3
    volumes:
      - db_volume:/var/lib/mysql
    container_name: db_volume
volumes:
  db_volume:
