apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "nullsuck-ip"
spec:
  backend:
    serviceName: app-svc
    servicePort: 3000